//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmWcfCrudList.Service.Domain
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Todo", Namespace="http://schemas.datacontract.org/2004/07/MvvmWcfCrudList.Service.Domain")]
    public partial class Todo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddedByField;
        
        private int CompletedPomodoriField;
        
        private System.DateTime CreateDtField;
        
        private System.DateTime DueDtField;
        
        private int EstimatedPomodoriField;
        
        private System.Guid IdField;
        
        private string TextField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddedBy
        {
            get
            {
                return this.AddedByField;
            }
            set
            {
                this.AddedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletedPomodori
        {
            get
            {
                return this.CompletedPomodoriField;
            }
            set
            {
                this.CompletedPomodoriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDt
        {
            get
            {
                return this.CreateDtField;
            }
            set
            {
                this.CreateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDt
        {
            get
            {
                return this.DueDtField;
            }
            set
            {
                this.DueDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedPomodori
        {
            get
            {
                return this.EstimatedPomodoriField;
            }
            set
            {
                this.EstimatedPomodoriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITodoService")]
public interface ITodoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Add", ReplyAction="http://tempuri.org/ITodoService/AddResponse")]
    string Add(MvvmWcfCrudList.Service.Domain.Todo todo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Add", ReplyAction="http://tempuri.org/ITodoService/AddResponse")]
    System.Threading.Tasks.Task<string> AddAsync(MvvmWcfCrudList.Service.Domain.Todo todo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Delete", ReplyAction="http://tempuri.org/ITodoService/DeleteResponse")]
    void Delete(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Delete", ReplyAction="http://tempuri.org/ITodoService/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/List", ReplyAction="http://tempuri.org/ITodoService/ListResponse")]
    MvvmWcfCrudList.Service.Domain.Todo[] List();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/List", ReplyAction="http://tempuri.org/ITodoService/ListResponse")]
    System.Threading.Tasks.Task<MvvmWcfCrudList.Service.Domain.Todo[]> ListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Update", ReplyAction="http://tempuri.org/ITodoService/UpdateResponse")]
    bool Update(MvvmWcfCrudList.Service.Domain.Todo todo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Update", ReplyAction="http://tempuri.org/ITodoService/UpdateResponse")]
    System.Threading.Tasks.Task<bool> UpdateAsync(MvvmWcfCrudList.Service.Domain.Todo todo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Get", ReplyAction="http://tempuri.org/ITodoService/GetResponse")]
    MvvmWcfCrudList.Service.Domain.Todo Get(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/Get", ReplyAction="http://tempuri.org/ITodoService/GetResponse")]
    System.Threading.Tasks.Task<MvvmWcfCrudList.Service.Domain.Todo> GetAsync(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITodoServiceChannel : ITodoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TodoServiceClient : System.ServiceModel.ClientBase<ITodoService>, ITodoService
{
    
    public TodoServiceClient()
    {
    }
    
    public TodoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TodoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TodoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TodoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Add(MvvmWcfCrudList.Service.Domain.Todo todo)
    {
        return base.Channel.Add(todo);
    }
    
    public System.Threading.Tasks.Task<string> AddAsync(MvvmWcfCrudList.Service.Domain.Todo todo)
    {
        return base.Channel.AddAsync(todo);
    }
    
    public void Delete(string id)
    {
        base.Channel.Delete(id);
    }
    
    public System.Threading.Tasks.Task DeleteAsync(string id)
    {
        return base.Channel.DeleteAsync(id);
    }
    
    public MvvmWcfCrudList.Service.Domain.Todo[] List()
    {
        return base.Channel.List();
    }
    
    public System.Threading.Tasks.Task<MvvmWcfCrudList.Service.Domain.Todo[]> ListAsync()
    {
        return base.Channel.ListAsync();
    }
    
    public bool Update(MvvmWcfCrudList.Service.Domain.Todo todo)
    {
        return base.Channel.Update(todo);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateAsync(MvvmWcfCrudList.Service.Domain.Todo todo)
    {
        return base.Channel.UpdateAsync(todo);
    }
    
    public MvvmWcfCrudList.Service.Domain.Todo Get(string id)
    {
        return base.Channel.Get(id);
    }
    
    public System.Threading.Tasks.Task<MvvmWcfCrudList.Service.Domain.Todo> GetAsync(string id)
    {
        return base.Channel.GetAsync(id);
    }
}
